const USER_REGISTER_LOADING = "loadingregister";
const USER_REGISTER_SUCCESS = "successregister";
const USER_REGISTER_ERROR = "errorregister";
const GET_USERDETAILS_LOADING = "getUSERDETAILSloading";
const GET_USERDETAILS_ERROR = "getUSERDETAILSerror";
const GET_USERDETAILS_SUCCESS = "getUSERDETAILSsuccess";
export {
  USER_REGISTER_LOADING,
  USER_REGISTER_SUCCESS,
  USER_REGISTER_ERROR,
  GET_USERDETAILS_LOADING,
  GET_USERDETAILS_ERROR,
  GET_USERDETAILS_SUCCESS,
};
